spring.application.name=backend
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/theses_mauritanie
spring.datasource.username=postgres
spring.datasource.password=veride@12345
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

## Configuration pour le téléchargement de fichiers
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=215MB

## Répertoire de stockage des fichiers
file.upload-dir=./uploads




